version: "3.5"
services:
  ssv:
    image: "ssv.ssv-prater.dnp.dappnode.eth:1.0.1"
    build:
      context: build
      args:
        UPSTREAM_VERSION: v1.0.0-rc.1
    restart: unless-stopped
    volumes:
      - "ssv:/data"
    ports:
      - "12514:12514/tcp"
      - "13514:13514/udp"
    environment:
      CONFIG_PATH: ./config.yml
      DB_PATH: /data/db
      NETWORK: jato-v2
      BUILDER_PROPOSALS: "false"
      OPERATOR_PRIVATE_KEY: ""
      P2P_TCP_PORT: 12514
      P2P_UDP_PORT: 13514
      LOG_LEVEL: info
      EXTRA_OPTS: ""
volumes:
  ssv: {}
