version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        UPSTREAM_VERSION: v1.3.4
    restart: unless-stopped
    volumes:
      - operator-data:/data/operator
    ports:
      - 12516:12516/tcp
      - 13516:13516/udp
    environment:
      BUILDER_PROPOSALS: "false"
      LOG_LEVEL: info
      EXTRA_OPTS: ""
      PRIVATE_KEY_PASS: ""
    image: operator.ssv.dnp.dappnode.eth:0.1.0
  dkg:
    build:
      context: dkg
      args:
        DGK_UPSTREAM_VERSION: v2.1.0
    restart: on-failure
    volumes:
      - operator-data:/data/operator
      - dkg-data:/data/dkg
    ports:
      - "14516:14516"
    environment:
      LOG_LEVEL: info
      OPERATOR_ID: ""
      EXTRA_OPTS: ""
    image: dkg.ssv.dnp.dappnode.eth:0.1.0
volumes:
  dkg-data: {}
  operator-data: {}
