version: "3.4"
services:
  ssv-prater.dnp.dappnode.eth:
    image: "ssv-prater.dnp.dappnode.eth:0.1.0"
    build:
      context: build
      args:
        UPSTREAM_VERSION: v0.2.1-rc.4
    restart: unless-stopped
    volumes:
      - "ssv:/data"
    ports:
      - "13001:13001"
      - 12001/udp
    environment:
      CONFIG_PATH: ./config.yml
      DB_PATH: /data/db
      NETWORK: prater
      BEACON_NODE_ADDR: "beacon-chain.prysm-prater.dappnode:3500"
      ETH1ADDR: "ws://goerli-geth.dappnode:8546"
      REGISTRY_CONTRACT_ADDR: "0x687fb596F3892904F879118e2113e1EEe8746C2E"
      OPERATOR_PRIVATE_KEY: ""
      LOG_LEVEL: info
      EXTRA_OPTS: ""
volumes:
  ssv: {}
