{
 "title": "SSV Operator Node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "ssv-node-v2-1,ssv-node-v2-2,ssv-node-v2-3,ssv-node-v2-4"
   },
   {
    "name": "explorer",
    "query": "https://explorer.ssv.network,https://explorer.stage.ssv.network"
   }
  ]
 },
 "panels": [
  { "title": "Validators Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validators (Attestation)",
   "type": "table",
   "description": "Information on attestation duties for all validators registered to an operator",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_stage{service=\"ssv-prater.dappnode\"}"
    },
    {
     "expr": "ssv:validator:ibft_highest_decided{service=\"ssv-prater.dappnode\"}"
    },
    {
     "expr": "ssv:network:connected_peers{service=\"ssv-prater.dappnode\"}"
    },
    {
     "expr": "ssv:validator:ibft_current_sequence{service=\"ssv-prater.dappnode\"}"
    },
    {
     "expr": "ssv:validator:ibft_round{service=\"ssv-prater.dappnode\"}"
    },
    {
     "expr": "ssv:validator:running_ibfts_count{service=\"ssv-prater.dappnode\"}"
    },
    {
     "expr": "ssv:validator:ibft_current_slot{service=\"ssv-prater.dappnode\"}"
    }
   ]
  },
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Current Health Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:beacon:node_status{service=\"ssv-prater.dappnode\"}",
     "legendFormat": "Beacon"
    },
    {
     "expr": "ssv:eth1:node_status{service=\"ssv-prater.dappnode\"}",
     "legendFormat": "ETH1"
    },
    {
     "expr": "ssv:node_status{service=\"ssv-prater.dappnode\"}",
     "legendFormat": "SSV Operator"
    }
   ]
  },
  { "title": "Process Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"ssv-prater.dappnode\"}",
     "legendFormat": "SSV-Prater"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{image!=\"\", package=\"ssv-prater.dnp.dappnode.eth\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "ssv-prater.dnp.dappnode.eth"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"ssv-prater.dappnode\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}